### ISSUE TITLE
Test on video reconstruction or generation

### ISSUE THREAD

**Issue by TikhonovDongqiudi** [rccchoudhury/rlt#3]
Hi,

Really impressed with the results your method has achieved in maintaining the semantic integrity of the videos. It's a commendable contribution to the field.
However, I am particularly interested in the reconstruction of video details, which is crucial for generative tasks. I was wondering if you have conducted experiments that specifically address the performance of your method in this aspect. Detailed reconstruction is often a challenging aspect of video generation, and insights into how your method handles this would be highly valuable.
If you have any experimental results or further analysis regarding detail reconstruction, I would be most grateful if you could share them.

Thanks.

**Comment by rccchoudhury** [comment]
Thanks so much for your kind words! We agree that reconstruction / generation would be incredibly valuable. However, it's not obvious how to do this with the current version of RLT - while the input is a fixed number of tokens, the output encoding consists of a variable number of tokens that is dependent on the input. This makes it hard to hook up "out of the box" to a diffusion model or autoregressive model since it doesn't play nicely with existing visual tokenizers like VQ-VAE/VQGAN/dVAE. As such, we don't have any results to share on this front.

However, we are starting work on this problem and will hopefully have a solution in the next couple of months :)
